
language: python
python:
  - 3.5
  - 3.6


install:
  - pip install -r requirements.txt
  - echo $AIRFLOW_HOME
  - echo $AIRFLOW_CONFIG
  - echo $TRAVIS_BUILD_ID
script:
  - airflow initdb
  - pytest tests
  - pytest --cov=./
after_success:
  - codecov --token=$CODECOV
