
language: python

sudo: false

python:
  - 3.5
  - 3.6

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

before_install:
  - pip install pipenv
install:
  - pipenv install
  - pipenv shell
script:
  - pytest tests
