
language: python

sudo: false

python:
  - 3.5
  - 3.6

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - AIRFLOW_CONFIG=$TRAVIS_BUILD_DIR/airflow.cfg

before_install:
  - pip install pipenv
  - pipenv install
install:
  - echo $AIRFLOW_HOME
script:
  - pipenv run pytest tests
